// Database of Origins in India (36 States & Union Territories)
const ORIGINS_DATABASE = [
    {
        "id": "AP",
        "name": "Andhra Pradesh (VGA)",
        "airport": "Vijayawada Airport",
        "code": "VGA",
        "lat": 16.5304,
        "lng": 80.7968
    },
    {
        "id": "AR",
        "name": "Arunachal Pradesh (HGI)",
        "airport": "Donyi Polo Airport",
        "code": "HGI",
        "lat": 26.9961,
        "lng": 93.6425
    },
    {
        "id": "AS",
        "name": "Assam (GAU)",
        "airport": "Guwahati Airport",
        "code": "GAU",
        "lat": 26.1061,
        "lng": 91.5859
    },
    {
        "id": "BR",
        "name": "Bihar (PAT)",
        "airport": "Patna Airport",
        "code": "PAT",
        "lat": 25.5913,
        "lng": 85.0882
    },
    {
        "id": "CG",
        "name": "Chhattisgarh (RPR)",
        "airport": "Raipur Airport",
        "code": "RPR",
        "lat": 21.1804,
        "lng": 81.7387
    },
    {
        "id": "GA",
        "name": "Goa (GOI)",
        "airport": "Dabolim Airport",
        "code": "GOI",
        "lat": 15.3808,
        "lng": 73.8314
    },
    {
        "id": "GJ",
        "name": "Gujarat (AMD)",
        "airport": "Sardar Vallabhbhai Airport",
        "code": "AMD",
        "lat": 23.0734,
        "lng": 72.6347
    },
    {
        "id": "HR",
        "name": "Haryana (IXC)",
        "airport": "Chandigarh Airport",
        "code": "IXC",
        "lat": 30.6734,
        "lng": 76.7885
    },
    {
        "id": "HP",
        "name": "Himachal Pradesh (DHM)",
        "airport": "Dharamshala Airport",
        "code": "DHM",
        "lat": 32.1651,
        "lng": 76.2634
    },
    {
        "id": "JH",
        "name": "Jharkhand (IXR)",
        "airport": "Ranchi Airport",
        "code": "IXR",
        "lat": 23.3142,
        "lng": 85.3218
    },
    {
        "id": "KA",
        "name": "Karnataka (BLR)",
        "airport": "Kempegowda Int Airport",
        "code": "BLR",
        "lat": 13.1986,
        "lng": 77.7068
    },
    {
        "id": "KL",
        "name": "Kerala (COK)",
        "airport": "Cochin International Airport",
        "code": "COK",
        "lat": 10.152,
        "lng": 76.4012
    },
    {
        "id": "MP",
        "name": "Madhya Pradesh (IDR)",
        "airport": "Indore Airport",
        "code": "IDR",
        "lat": 22.7217,
        "lng": 75.8011
    },
    {
        "id": "MH",
        "name": "Maharashtra (BOM)",
        "airport": "Chhatrapati Shivaji Airport",
        "code": "BOM",
        "lat": 19.0896,
        "lng": 72.8656
    },
    {
        "id": "MN",
        "name": "Manipur (IMF)",
        "airport": "Imphal Airport",
        "code": "IMF",
        "lat": 24.76,
        "lng": 93.8967
    },
    {
        "id": "ML",
        "name": "Meghalaya (SHL)",
        "airport": "Shillong Airport",
        "code": "SHL",
        "lat": 25.7025,
        "lng": 91.9786
    },
    {
        "id": "MZ",
        "name": "Mizoram (AJL)",
        "airport": "Aizawl Airport",
        "code": "AJL",
        "lat": 23.8368,
        "lng": 92.6186
    },
    {
        "id": "NL",
        "name": "Nagaland (DMU)",
        "airport": "Dimapur Airport",
        "code": "DMU",
        "lat": 25.8837,
        "lng": 93.7712
    },
    {
        "id": "OD",
        "name": "Odisha (BBI)",
        "airport": "Bhubaneswar Airport",
        "code": "BBI",
        "lat": 20.2444,
        "lng": 85.8178
    },
    {
        "id": "PB",
        "name": "Punjab (ATQ)",
        "airport": "Amritsar Airport",
        "code": "ATQ",
        "lat": 31.7096,
        "lng": 74.7973
    },
    {
        "id": "RJ",
        "name": "Rajasthan (JAI)",
        "airport": "Jaipur Airport",
        "code": "JAI",
        "lat": 26.8242,
        "lng": 75.8122
    },
    {
        "id": "SK",
        "name": "Sikkim (PYG)",
        "airport": "Pakyong Airport",
        "code": "PYG",
        "lat": 27.2281,
        "lng": 88.5917
    },
    {
        "id": "TN",
        "name": "Tamil Nadu (MAA)",
        "airport": "Chennai International Airport",
        "code": "MAA",
        "lat": 12.9941,
        "lng": 80.1709
    },
    {
        "id": "TG",
        "name": "Telangana (HYD)",
        "airport": "Rajiv Gandhi Int Airport",
        "code": "HYD",
        "lat": 17.2403,
        "lng": 78.4294
    },
    {
        "id": "TR",
        "name": "Tripura (IXA)",
        "airport": "Agartala Airport",
        "code": "IXA",
        "lat": 23.8869,
        "lng": 91.2405
    },
    {
        "id": "UP",
        "name": "Uttar Pradesh (LKO)",
        "airport": "Lucknow Airport",
        "code": "LKO",
        "lat": 26.7606,
        "lng": 80.8893
    },
    {
        "id": "UT",
        "name": "Uttarakhand (DED)",
        "airport": "Dehradun Airport",
        "code": "DED",
        "lat": 30.1897,
        "lng": 78.1803
    },
    {
        "id": "WB",
        "name": "West Bengal (CCU)",
        "airport": "Netaji Subhash Bose Airport",
        "code": "CCU",
        "lat": 22.6547,
        "lng": 88.4467
    },
    {
        "id": "AN",
        "name": "Andaman & Nicobar (IXZ)",
        "airport": "Port Blair Airport",
        "code": "IXZ",
        "lat": 11.641,
        "lng": 92.7297
    },
    {
        "id": "CH",
        "name": "Chandigarh (IXC)",
        "airport": "Chandigarh Airport",
        "code": "IXC",
        "lat": 30.6734,
        "lng": 76.7885
    },
    {
        "id": "DN",
        "name": "Dadra & Nagar Haveli (DIU)",
        "airport": "Diu Airport",
        "code": "DIU",
        "lat": 20.7126,
        "lng": 70.9218
    },
    {
        "id": "DL",
        "name": "Delhi (DEL)",
        "airport": "Indira Gandhi Int Airport",
        "code": "DEL",
        "lat": 28.5562,
        "lng": 77.1
    },
    {
        "id": "JK",
        "name": "Jammu & Kashmir (SXR)",
        "airport": "Srinagar Airport",
        "code": "SXR",
        "lat": 33.9873,
        "lng": 74.7744
    },
    {
        "id": "LA",
        "name": "Ladakh (IXL)",
        "airport": "Leh Airport",
        "code": "IXL",
        "lat": 34.1359,
        "lng": 77.5463
    },
    {
        "id": "LD",
        "name": "Lakshadweep (AGX)",
        "airport": "Agatti Airport",
        "code": "AGX",
        "lat": 10.8239,
        "lng": 72.1762
    },
    {
        "id": "PY",
        "name": "Puducherry (PNY)",
        "airport": "Puducherry Airport",
        "code": "PNY",
        "lat": 11.9667,
        "lng": 79.8105
    }
];

// Database of Destinations (144 Countries with eovisas.com details)
const DESTINATIONS_DATABASE = [
    {
        "id": "KBL",
        "name": "Afghanistan",
        "countryName": "Afghanistan",
        "flag": "🇦🇫",
        "code": "KBL",
        "airport": "Kabul International Airport",
        "lat": 34.5658,
        "lng": 69.2125,
        "visaType": "Sticker Visa",
        "visaProcess": "7 to 14 working days",
        "timezoneOffset": 4.5
    },
    {
        "id": "TIA",
        "name": "Albania",
        "countryName": "Albania",
        "flag": "🇦🇱",
        "code": "TIA",
        "airport": "Tirana International Airport Nënë Tereza",
        "lat": 41.4147,
        "lng": 19.7206,
        "visaType": "e-Visas",
        "visaProcess": "15-30 working days",
        "timezoneOffset": 2
    },
    {
        "id": "ALG",
        "name": "Algeria",
        "countryName": "Algeria",
        "flag": "🇩🇿",
        "code": "ALG",
        "airport": "Houari Boumediene Airport",
        "lat": 36.691,
        "lng": 3.2154,
        "visaType": "Sticker Visa",
        "visaProcess": "5 to 10 working days",
        "timezoneOffset": 1
    },
    {
        "id": "BCN",
        "name": "Andorra",
        "countryName": "Andorra",
        "flag": "🇦🇩",
        "code": "BCN",
        "airport": "Barcelona Airport (via Spain)",
        "lat": 42.5063,
        "lng": 1.5218,
        "visaType": "Sticker Visa",
        "visaProcess": "15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "LAD",
        "name": "Angola",
        "countryName": "Angola",
        "flag": "🇦🇴",
        "code": "LAD",
        "airport": "Quatro de Fevereiro Airport",
        "lat": -8.8583,
        "lng": 13.2312,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 1
    },
    {
        "id": "ANU",
        "name": "Antigua and Barbuda",
        "countryName": "Antigua and Barbuda",
        "flag": "🇦🇬",
        "code": "ANU",
        "airport": "V. C. Bird International Airport",
        "lat": 17.1367,
        "lng": -61.7927,
        "visaType": "Visa Free",
        "visaProcess": "15-30 working days",
        "timezoneOffset": -4
    },
    {
        "id": "EZE",
        "name": "Argentina",
        "countryName": "Argentina",
        "flag": "🇦🇷",
        "code": "EZE",
        "airport": "Ministro Pistarini International Airport",
        "lat": -34.8222,
        "lng": -58.5358,
        "visaType": "e-Visas",
        "visaProcess": "3-6 weeks",
        "timezoneOffset": -3
    },
    {
        "id": "EVN",
        "name": "Armenia",
        "countryName": "Armenia",
        "flag": "🇦🇲",
        "code": "EVN",
        "airport": "Zvartnots International Airport",
        "lat": 40.1473,
        "lng": 44.3959,
        "visaType": "e-Visas",
        "visaProcess": "2-3 working days",
        "timezoneOffset": 4
    },
    {
        "id": "SYD",
        "name": "Australia",
        "countryName": "Australia",
        "flag": "🇦🇺",
        "code": "SYD",
        "airport": "Sydney Kingsford Smith Airport",
        "lat": -33.9461,
        "lng": 151.1772,
        "visaType": "e-Visas",
        "visaProcess": "20-45 working days",
        "timezoneOffset": 10
    },
    {
        "id": "VIE",
        "name": "Austria",
        "countryName": "Austria",
        "flag": "🇦🇹",
        "code": "VIE",
        "airport": "Vienna International Airport",
        "lat": 48.1103,
        "lng": 16.5697,
        "visaType": "Sticker Visa",
        "visaProcess": "15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "GYD",
        "name": "Azerbaijan",
        "countryName": "Azerbaijan",
        "flag": "🇦🇿",
        "code": "GYD",
        "airport": "Heydar Aliyev Int Airport",
        "lat": 40.4675,
        "lng": 50.0467,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 4
    },
    {
        "id": "NAS",
        "name": "Bahamas",
        "countryName": "Bahamas",
        "flag": "🇧🇸",
        "code": "NAS",
        "airport": "Lynden Pindling International Airport",
        "lat": 25.0389,
        "lng": -77.4638,
        "visaType": "Sticker Visa",
        "visaProcess": "7-15 working days",
        "timezoneOffset": -5
    },
    {
        "id": "BAH",
        "name": "Bahrain",
        "countryName": "Bahrain",
        "flag": "🇧🇭",
        "code": "BAH",
        "airport": "Bahrain International Airport",
        "lat": 26.2708,
        "lng": 50.6336,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 3
    },
    {
        "id": "DAC",
        "name": "Bangladesh",
        "countryName": "Bangladesh",
        "flag": "🇧🇩",
        "code": "DAC",
        "airport": "Hazrat Shahjalal Int Airport",
        "lat": 23.8433,
        "lng": 90.3978,
        "visaType": "Sticker Visa",
        "visaProcess": "5 to 7 working days",
        "timezoneOffset": 6
    },
    {
        "id": "BGI",
        "name": "Barbados",
        "countryName": "Barbados",
        "flag": "🇧🇧",
        "code": "BGI",
        "airport": "Grantley Adams International Airport",
        "lat": 13.0747,
        "lng": -59.4925,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "MSQ",
        "name": "Belarus",
        "countryName": "Belarus",
        "flag": "🇧🇾",
        "code": "MSQ",
        "airport": "Minsk National Airport",
        "lat": 53.8825,
        "lng": 28.0307,
        "visaType": "e-Visas",
        "visaProcess": "5 Working Days",
        "timezoneOffset": 3
    },
    {
        "id": "BRU",
        "name": "Belgium",
        "countryName": "Belgium",
        "flag": "🇧🇪",
        "code": "BRU",
        "airport": "Brussels Airport",
        "lat": 50.901,
        "lng": 4.4844,
        "visaType": "Sticker Visa",
        "visaProcess": "15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "BZE",
        "name": "Belize",
        "countryName": "Belize",
        "flag": "🇧🇿",
        "code": "BZE",
        "airport": "Philip S. W. Goldson Int Airport",
        "lat": 17.5391,
        "lng": -88.3082,
        "visaType": "Sticker Visa",
        "visaProcess": "15-20 working days",
        "timezoneOffset": -6
    },
    {
        "id": "COO",
        "name": "Benin",
        "countryName": "Benin",
        "flag": "🇧🇯",
        "code": "COO",
        "airport": "Cotonou Cadjehoun Airport",
        "lat": 6.3572,
        "lng": 2.3844,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 1
    },
    {
        "id": "PBH",
        "name": "Bhutan",
        "countryName": "Bhutan",
        "flag": "🇧🇹",
        "code": "PBH",
        "airport": "Paro Airport",
        "lat": 27.4026,
        "lng": 89.4246,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 6
    },
    {
        "id": "LPB",
        "name": "Bolivia",
        "countryName": "Bolivia",
        "flag": "🇧🇴",
        "code": "LPB",
        "airport": "El Alto International Airport",
        "lat": -16.5133,
        "lng": -68.1922,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "SJJ",
        "name": "Bosnia and Herzegovina",
        "countryName": "Bosnia and Herzegovina",
        "flag": "🇧🇦",
        "code": "SJJ",
        "airport": "Sarajevo International Airport",
        "lat": 43.8242,
        "lng": 18.3314,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 Working days",
        "timezoneOffset": 2
    },
    {
        "id": "GBE",
        "name": "Botswana",
        "countryName": "Botswana",
        "flag": "🇧🇼",
        "code": "GBE",
        "airport": "Sir Seretse Khama Int Airport",
        "lat": -24.5552,
        "lng": 25.9184,
        "visaType": "e-Visas",
        "visaProcess": "15 to 30 working days",
        "timezoneOffset": 2
    },
    {
        "id": "GRU",
        "name": "Brazil",
        "countryName": "Brazil",
        "flag": "🇧🇷",
        "code": "GRU",
        "airport": "São Paulo/Guarulhos Int Airport",
        "lat": -23.4356,
        "lng": -46.4731,
        "visaType": "Sticker Visa",
        "visaProcess": "7-15 working days",
        "timezoneOffset": -3
    },
    {
        "id": "BWN",
        "name": "Brunei",
        "countryName": "Brunei",
        "flag": "🇧🇳",
        "code": "BWN",
        "airport": "Brunei International Airport",
        "lat": 4.9442,
        "lng": 114.9283,
        "visaType": "Sticker Visa",
        "visaProcess": "5-6 working days",
        "timezoneOffset": 8
    },
    {
        "id": "SOF",
        "name": "Bulgaria",
        "countryName": "Bulgaria",
        "flag": "🇧🇬",
        "code": "SOF",
        "airport": "Sofia Airport",
        "lat": 42.6951,
        "lng": 23.4075,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 Working days",
        "timezoneOffset": 3
    },
    {
        "id": "OUA",
        "name": "Burkina Faso",
        "countryName": "Burkina Faso",
        "flag": "🇧🇫",
        "code": "OUA",
        "airport": "Ouagadougou Airport",
        "lat": 12.3532,
        "lng": -1.5124,
        "visaType": "Sticker Visa",
        "visaProcess": "3 to 10 working days",
        "timezoneOffset": 0
    },
    {
        "id": "BJM",
        "name": "Burundi",
        "countryName": "Burundi",
        "flag": "🇧🇮",
        "code": "BJM",
        "airport": "Bujumbura International Airport",
        "lat": -3.324,
        "lng": 29.3185,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 2
    },
    {
        "id": "SID",
        "name": "Cabo Verde",
        "countryName": "Cape Verde",
        "flag": "🇨🇻",
        "code": "SID",
        "airport": "Amílcar Cabral International Airport",
        "lat": 16.7414,
        "lng": -22.9494,
        "visaType": "Sticker Visa",
        "visaProcess": "7 to 10 business days",
        "timezoneOffset": -1
    },
    {
        "id": "PNH",
        "name": "Cambodia",
        "countryName": "Cambodia",
        "flag": "🇰🇭",
        "code": "PNH",
        "airport": "Phnom Penh International Airport",
        "lat": 11.5466,
        "lng": 104.8441,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 7
    },
    {
        "id": "NSI",
        "name": "Cameroon",
        "countryName": "Cameroon",
        "flag": "🇨🇲",
        "code": "NSI",
        "airport": "Yaoundé Nsimalen Int Airport",
        "lat": 3.8373,
        "lng": 11.5533,
        "visaType": "e-Visas",
        "visaProcess": "3-10 working days",
        "timezoneOffset": 1
    },
    {
        "id": "YYZ",
        "name": "Canada",
        "countryName": "Canada",
        "flag": "🇨🇦",
        "code": "YYZ",
        "airport": "Toronto Pearson International Airport",
        "lat": 43.6777,
        "lng": -79.6248,
        "visaType": "Sticker Visa",
        "visaProcess": "25-35 working days",
        "timezoneOffset": -5
    },
    {
        "id": "BGF",
        "name": "Central African Republic",
        "countryName": "Central African Republic",
        "flag": "🇨🇫",
        "code": "BGF",
        "airport": "Bangui M'Poko International Airport",
        "lat": 4.3984,
        "lng": 18.5188,
        "visaType": "Sticker Visa",
        "visaProcess": "5 to 10 working days",
        "timezoneOffset": 1
    },
    {
        "id": "NDJ",
        "name": "Chad",
        "countryName": "Chad",
        "flag": "🇹🇩",
        "code": "NDJ",
        "airport": "N'Djamena International Airport",
        "lat": 12.1319,
        "lng": 15.0333,
        "visaType": "Sticker Visa",
        "visaProcess": "7 to 10 working days",
        "timezoneOffset": 1
    },
    {
        "id": "SCL",
        "name": "Chile",
        "countryName": "Chile",
        "flag": "🇨🇱",
        "code": "SCL",
        "airport": "Arturo Merino Benítez Int Airport",
        "lat": -33.393,
        "lng": -70.7858,
        "visaType": "e-Visas",
        "visaProcess": "15-20 working days",
        "timezoneOffset": -3
    },
    {
        "id": "PEK",
        "name": "China",
        "countryName": "China",
        "flag": "🇨🇳",
        "code": "PEK",
        "airport": "Beijing Capital Airport",
        "lat": 40.0799,
        "lng": 116.5976,
        "visaType": "Sticker Visa",
        "visaProcess": "4-6 working days",
        "timezoneOffset": 8
    },
    {
        "id": "BOG",
        "name": "Colombia",
        "countryName": "Colombia",
        "flag": "🇨🇴",
        "code": "BOG",
        "airport": "El Dorado International Airport",
        "lat": 4.7016,
        "lng": -74.1469,
        "visaType": "e-Visas",
        "visaProcess": "5-15 working days",
        "timezoneOffset": -5
    },
    {
        "id": "HAH",
        "name": "Comoros",
        "countryName": "Comoros",
        "flag": "🇰🇲",
        "code": "HAH",
        "airport": "Prince Said Ibrahim Int Airport",
        "lat": -11.476,
        "lng": 43.2714,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 3
    },
    {
        "id": "SJO",
        "name": "Costa Rica",
        "countryName": "Costa Rica",
        "flag": "🇨🇷",
        "code": "SJO",
        "airport": "Juan Santamaría International Airport",
        "lat": 9.9939,
        "lng": -84.2089,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 working days",
        "timezoneOffset": -6
    },
    {
        "id": "ABJ",
        "name": "Cote d’Ivoire",
        "countryName": "Ivory Coast",
        "flag": "🇨🇮",
        "code": "ABJ",
        "airport": "Félix-Houphouët-Boigny Int Airport",
        "lat": 5.2614,
        "lng": -3.9264,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 0
    },
    {
        "id": "ZAG",
        "name": "Croatia",
        "countryName": "Croatia",
        "flag": "🇭🇷",
        "code": "ZAG",
        "airport": "Zagreb Airport",
        "lat": 45.7429,
        "lng": 16.0688,
        "visaType": "Sticker Visa",
        "visaProcess": "15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "HAV",
        "name": "Cuba",
        "countryName": "Cuba",
        "flag": "🇨🇺",
        "code": "HAV",
        "airport": "José Martí International Airport",
        "lat": 22.9892,
        "lng": -82.4091,
        "visaType": "e-Visas",
        "visaProcess": "5-7 working days",
        "timezoneOffset": -5
    },
    {
        "id": "LCA",
        "name": "Cyprus",
        "countryName": "Cyprus",
        "flag": "🇨🇾",
        "code": "LCA",
        "airport": "Larnaca International Airport",
        "lat": 34.8789,
        "lng": 33.6249,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 working days",
        "timezoneOffset": 3
    },
    {
        "id": "PRG",
        "name": "Czech Republic",
        "countryName": "Czech Republic",
        "flag": "🇨🇿",
        "code": "PRG",
        "airport": "Václav Havel Airport Prague",
        "lat": 50.1008,
        "lng": 14.26,
        "visaType": "Sticker Visa",
        "visaProcess": "15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "FIH",
        "name": "Democratic Republic of the Congo",
        "countryName": "Democratic Republic of the Congo",
        "flag": "🇨🇩",
        "code": "FIH",
        "airport": "N'djili Airport",
        "lat": -4.3856,
        "lng": 15.4447,
        "visaType": "Sticker Visa",
        "visaProcess": "10 to 12 working days",
        "timezoneOffset": 1
    },
    {
        "id": "CPH",
        "name": "Denmark",
        "countryName": "Denmark",
        "flag": "🇩🇰",
        "code": "CPH",
        "airport": "Copenhagen Airport",
        "lat": 55.618,
        "lng": 12.6508,
        "visaType": "Sticker Visa",
        "visaProcess": "15-30 working days",
        "timezoneOffset": 2
    },
    {
        "id": "JIB",
        "name": "Djibouti",
        "countryName": "Djibouti",
        "flag": "🇩🇯",
        "code": "JIB",
        "airport": "Djibouti-Ambouli International Airport",
        "lat": 11.5475,
        "lng": 43.1594,
        "visaType": "e-Visas",
        "visaProcess": "3 working days",
        "timezoneOffset": 3
    },
    {
        "id": "DOM",
        "name": "Dominica",
        "countryName": "Dominica",
        "flag": "🇩🇲",
        "code": "DOM",
        "airport": "Douglas-Charles Airport",
        "lat": 15.547,
        "lng": -61.3,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "SDQ",
        "name": "Dominican Republic",
        "countryName": "Dominican Republic",
        "flag": "🇩🇴",
        "code": "SDQ",
        "airport": "Las Américas International Airport",
        "lat": 18.4297,
        "lng": -69.6689,
        "visaType": "Sticker Visa",
        "visaProcess": "7-10 working days",
        "timezoneOffset": -4
    },
    {
        "id": "DXB",
        "name": "Dubai (UAE)",
        "countryName": "United Arab Emirates",
        "flag": "🇦🇪",
        "code": "DXB",
        "airport": "Dubai International Airport",
        "lat": 25.2532,
        "lng": 55.3657,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 4
    },
    {
        "id": "UIO",
        "name": "Ecuador",
        "countryName": "Ecuador",
        "flag": "🇪🇨",
        "code": "UIO",
        "airport": "Mariscal Sucre International Airport",
        "lat": -0.1228,
        "lng": -78.3575,
        "visaType": "e-Visas",
        "visaProcess": "5 to 10 working days",
        "timezoneOffset": -5
    },
    {
        "id": "CAI",
        "name": "Egypt",
        "countryName": "Egypt",
        "flag": "🇪🇬",
        "code": "CAI",
        "airport": "Cairo International Airport",
        "lat": 30.1219,
        "lng": 31.4056,
        "visaType": "e-Visas",
        "visaProcess": "3-7 working days",
        "timezoneOffset": 3
    },
    {
        "id": "SAL",
        "name": "El Salvador",
        "countryName": "El Salvador",
        "flag": "🇸🇻",
        "code": "SAL",
        "airport": "Monseñor Óscar Arnulfo Romero Airport",
        "lat": 13.4409,
        "lng": -89.0558,
        "visaType": "Visa Free",
        "visaProcess": "2-3 working days",
        "timezoneOffset": -6
    },
    {
        "id": "SSG",
        "name": "Equatorial Guinea",
        "countryName": "Equatorial Guinea",
        "flag": "🇬🇶",
        "code": "SSG",
        "airport": "Malabo Airport",
        "lat": 3.7553,
        "lng": 8.7088,
        "visaType": "e-Visas",
        "visaProcess": "1 to 3 working days",
        "timezoneOffset": 1
    },
    {
        "id": "ASM",
        "name": "Eritrea",
        "countryName": "Eritrea",
        "flag": "🇪🇷",
        "code": "ASM",
        "airport": "Asmara International Airport",
        "lat": 15.2911,
        "lng": 38.9103,
        "visaType": "Sticker Visa",
        "visaProcess": "12 – 14 working days",
        "timezoneOffset": 3
    },
    {
        "id": "TLL",
        "name": "Estonia",
        "countryName": "Estonia",
        "flag": "🇪🇪",
        "code": "TLL",
        "airport": "Tallinn Airport",
        "lat": 59.4133,
        "lng": 24.8328,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 Working days",
        "timezoneOffset": 3
    },
    {
        "id": "SHO",
        "name": "Eswatini",
        "countryName": "Swaziland",
        "flag": "🇸🇿",
        "code": "SHO",
        "airport": "King Mswati III Int Airport",
        "lat": -26.3386,
        "lng": 31.3075,
        "visaType": "Sticker Visa",
        "visaProcess": "2 to 5 business days",
        "timezoneOffset": 2
    },
    {
        "id": "ADD",
        "name": "Ethiopia",
        "countryName": "Ethiopia",
        "flag": "🇪🇹",
        "code": "ADD",
        "airport": "Addis Ababa Bole Int Airport",
        "lat": 8.9779,
        "lng": 38.7993,
        "visaType": "e-Visas",
        "visaProcess": "3 working days",
        "timezoneOffset": 3
    },
    {
        "id": "NAN",
        "name": "Fiji",
        "countryName": "Fiji",
        "flag": "🇫🇯",
        "code": "NAN",
        "airport": "Nadi International Airport",
        "lat": -17.7554,
        "lng": 177.4434,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 12
    },
    {
        "id": "HEL",
        "name": "Finland",
        "countryName": "Finland",
        "flag": "🇫🇮",
        "code": "HEL",
        "airport": "Helsinki Airport",
        "lat": 60.3172,
        "lng": 24.9633,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 Working days",
        "timezoneOffset": 3
    },
    {
        "id": "CDG",
        "name": "France",
        "countryName": "France",
        "flag": "🇫🇷",
        "code": "CDG",
        "airport": "Charles de Gaulle Airport",
        "lat": 49.0097,
        "lng": 2.5479,
        "visaType": "Sticker Visa",
        "visaProcess": "5 to 15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "LBV",
        "name": "Gabon",
        "countryName": "Gabon",
        "flag": "🇬🇦",
        "code": "LBV",
        "airport": "Libreville Leon M'ba Int Airport",
        "lat": 0.4586,
        "lng": 9.4122,
        "visaType": "e-Visas",
        "visaProcess": "2-3 working days",
        "timezoneOffset": 1
    },
    {
        "id": "BJL",
        "name": "Gambia",
        "countryName": "Gambia",
        "flag": "🇬🇲",
        "code": "BJL",
        "airport": "Banjul International Airport",
        "lat": 13.338,
        "lng": -16.6522,
        "visaType": "e-Visas",
        "visaProcess": "3 to 5 working days",
        "timezoneOffset": 0
    },
    {
        "id": "TBS",
        "name": "Georgia",
        "countryName": "Georgia",
        "flag": "🇬🇪",
        "code": "TBS",
        "airport": "Tbilisi International Airport",
        "lat": 41.6702,
        "lng": 44.9547,
        "visaType": "e-Visas",
        "visaProcess": "3-7 working days",
        "timezoneOffset": 4
    },
    {
        "id": "FRA",
        "name": "Germany",
        "countryName": "Germany",
        "flag": "🇩🇪",
        "code": "FRA",
        "airport": "Frankfurt Airport",
        "lat": 50.0379,
        "lng": 8.5622,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 Working days",
        "timezoneOffset": 2
    },
    {
        "id": "ACC",
        "name": "Ghana",
        "countryName": "Ghana",
        "flag": "🇬🇭",
        "code": "ACC",
        "airport": "Kotoka International Airport",
        "lat": 5.6051,
        "lng": -0.1668,
        "visaType": "Sticker Visa",
        "visaProcess": "3 to 4 working days",
        "timezoneOffset": 0
    },
    {
        "id": "ATH",
        "name": "Greece",
        "countryName": "Greece",
        "flag": "🇬🇷",
        "code": "ATH",
        "airport": "Athens International Airport",
        "lat": 37.9356,
        "lng": 23.9484,
        "visaType": "Sticker Visa",
        "visaProcess": "15-20 working days",
        "timezoneOffset": 3
    },
    {
        "id": "GND",
        "name": "Grenada",
        "countryName": "Grenada",
        "flag": "🇬🇩",
        "code": "GND",
        "airport": "Maurice Bishop International Airport",
        "lat": 12.0042,
        "lng": -61.7861,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "GUA",
        "name": "Guatemala",
        "countryName": "Guatemala",
        "flag": "🇬🇹",
        "code": "GUA",
        "airport": "La Aurora International Airport",
        "lat": 14.5833,
        "lng": -90.5275,
        "visaType": "Sticker Visa",
        "visaProcess": "5-15 working days",
        "timezoneOffset": -6
    },
    {
        "id": "CKY",
        "name": "Guinea",
        "countryName": "Guinea",
        "flag": "🇬🇳",
        "code": "CKY",
        "airport": "Conakry International Airport",
        "lat": 9.5769,
        "lng": -13.612,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 0
    },
    {
        "id": "OXB",
        "name": "Guinea-Bissau",
        "countryName": "Guinea-Bissau",
        "flag": "🇬🇼",
        "code": "OXB",
        "airport": "Osvaldo Vieira International Airport",
        "lat": 11.8906,
        "lng": -15.6528,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 0
    },
    {
        "id": "GEO",
        "name": "Guyana",
        "countryName": "Guyana",
        "flag": "🇬🇾",
        "code": "GEO",
        "airport": "Cheddi Jagan International Airport",
        "lat": 6.5019,
        "lng": -58.2525,
        "visaType": "e-Visas",
        "visaProcess": "6-10 working days",
        "timezoneOffset": -4
    },
    {
        "id": "PAP",
        "name": "Haiti",
        "countryName": "Haiti",
        "flag": "🇭🇹",
        "code": "PAP",
        "airport": "Toussaint Louverture Int Airport",
        "lat": 18.58,
        "lng": -72.2925,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -5
    },
    {
        "id": "SAP",
        "name": "Honduras",
        "countryName": "Honduras",
        "flag": "🇭🇳",
        "code": "SAP",
        "airport": "Ramón Villeda Morales Int Airport",
        "lat": 15.4525,
        "lng": -87.9333,
        "visaType": "Sticker Visa",
        "visaProcess": "7-15 working days",
        "timezoneOffset": -6
    },
    {
        "id": "HKG",
        "name": "Hong Kong",
        "countryName": "Hong Kong",
        "flag": "🇭🇰",
        "code": "HKG",
        "airport": "Hong Kong International Airport",
        "lat": 22.308,
        "lng": 113.9185,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 8
    },
    {
        "id": "BUD",
        "name": "Hungary",
        "countryName": "Hungary",
        "flag": "🇭🇺",
        "code": "BUD",
        "airport": "Budapest Ferenc Liszt Int Airport",
        "lat": 47.4369,
        "lng": 19.2556,
        "visaType": "Sticker Visa",
        "visaProcess": "15 Working Days",
        "timezoneOffset": 2
    },
    {
        "id": "KEF",
        "name": "Iceland",
        "countryName": "Iceland",
        "flag": "🇮🇸",
        "code": "KEF",
        "airport": "Keflavík International Airport",
        "lat": 63.985,
        "lng": -22.6056,
        "visaType": "Sticker Visa",
        "visaProcess": "20-30 Working days",
        "timezoneOffset": 0
    },
    {
        "id": "CGK",
        "name": "Indonesia",
        "countryName": "Indonesia",
        "flag": "🇮🇩",
        "code": "CGK",
        "airport": "Soekarno–Hatta International Airport",
        "lat": -6.1256,
        "lng": 106.6558,
        "visaType": "Visa on Arrival",
        "visaProcess": "1 to 2 working days",
        "timezoneOffset": 7
    },
    {
        "id": "IKA",
        "name": "Iran",
        "countryName": "Iran",
        "flag": "🇮🇷",
        "code": "IKA",
        "airport": "Tehran Imam Khomeini Int Airport",
        "lat": 35.4161,
        "lng": 51.1522,
        "visaType": "Sticker Visa",
        "visaProcess": "7-10 working days",
        "timezoneOffset": 3.5
    },
    {
        "id": "BGW",
        "name": "Iraq",
        "countryName": "Iraq",
        "flag": "🇮🇶",
        "code": "BGW",
        "airport": "Baghdad International Airport",
        "lat": 33.2625,
        "lng": 44.2347,
        "visaType": "Sticker Visa",
        "visaProcess": "7-20 working days",
        "timezoneOffset": 3
    },
    {
        "id": "DUB",
        "name": "Ireland",
        "countryName": "Ireland",
        "flag": "🇮🇪",
        "code": "DUB",
        "airport": "Dublin Airport",
        "lat": 53.4264,
        "lng": -6.2699,
        "visaType": "Sticker Visa",
        "visaProcess": "4-6 weeks",
        "timezoneOffset": 1
    },
    {
        "id": "TLV",
        "name": "Israel",
        "countryName": "Israel",
        "flag": "🇮🇱",
        "code": "TLV",
        "airport": "Ben Gurion Airport",
        "lat": 32.0094,
        "lng": 34.8769,
        "visaType": "e-Visas",
        "visaProcess": "7-15 working days",
        "timezoneOffset": 3
    },
    {
        "id": "FCO",
        "name": "Italy",
        "countryName": "Italy",
        "flag": "🇮🇹",
        "code": "FCO",
        "airport": "Leonardo da Vinci–Fiumicino Airport",
        "lat": 41.8003,
        "lng": 12.2389,
        "visaType": "Sticker Visa",
        "visaProcess": "15-20 working days",
        "timezoneOffset": 2
    },
    {
        "id": "KIN",
        "name": "Jamaica",
        "countryName": "Jamaica",
        "flag": "🇯🇲",
        "code": "KIN",
        "airport": "Norman Manley International Airport",
        "lat": 17.9357,
        "lng": -76.7874,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -5
    },
    {
        "id": "HND",
        "name": "Japan",
        "countryName": "Japan",
        "flag": "🇯🇵",
        "code": "HND",
        "airport": "Tokyo Haneda Airport",
        "lat": 35.5494,
        "lng": 139.7798,
        "visaType": "Sticker Visa",
        "visaProcess": "5-10 working days",
        "timezoneOffset": 9
    },
    {
        "id": "AMM",
        "name": "Jordan",
        "countryName": "Jordan",
        "flag": "🇯🇴",
        "code": "AMM",
        "airport": "Queen Alia International Airport",
        "lat": 31.7225,
        "lng": 35.9933,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 3
    },
    {
        "id": "NQZ",
        "name": "Kazakhstan",
        "countryName": "Kazakhstan",
        "flag": "🇰🇿",
        "code": "NQZ",
        "airport": "Nursultan Nazarbayev Int Airport",
        "lat": 51.0222,
        "lng": 71.4672,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 5
    },
    {
        "id": "NBO",
        "name": "Kenya",
        "countryName": "Kenya",
        "flag": "🇰🇪",
        "code": "NBO",
        "airport": "Jomo Kenyatta Int Airport",
        "lat": -1.3192,
        "lng": 36.9275,
        "visaType": "e-Visas",
        "visaProcess": "2-3 working days",
        "timezoneOffset": 3
    },
    {
        "id": "TRW",
        "name": "Kiribati",
        "countryName": "Kiribati",
        "flag": "🇰🇮",
        "code": "TRW",
        "airport": "Bonriki International Airport",
        "lat": 1.3811,
        "lng": 172.9753,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 12
    },
    {
        "id": "PRN",
        "name": "Kosovo",
        "countryName": "Kosovo",
        "flag": "🇽🇰",
        "code": "PRN",
        "airport": "Pristina International Airport",
        "lat": 42.5728,
        "lng": 21.0358,
        "visaType": "Sticker Visa",
        "visaProcess": "3-4 Weeks",
        "timezoneOffset": 2
    },
    {
        "id": "KWI",
        "name": "Kuwait",
        "countryName": "Kuwait",
        "flag": "🇰🇼",
        "code": "KWI",
        "airport": "Kuwait International Airport",
        "lat": 29.2244,
        "lng": 47.9689,
        "visaType": "e-Visas",
        "visaProcess": "3-7 working days",
        "timezoneOffset": 3
    },
    {
        "id": "FRU",
        "name": "Kyrgyzstan",
        "countryName": "Kyrgyzstan",
        "flag": "🇰🇬",
        "code": "FRU",
        "airport": "Manas International Airport",
        "lat": 43.0614,
        "lng": 74.4776,
        "visaType": "e-Visas",
        "visaProcess": "2-3 working days",
        "timezoneOffset": 6
    },
    {
        "id": "VTE",
        "name": "Laos",
        "countryName": "Laos",
        "flag": "🇱🇦",
        "code": "VTE",
        "airport": "Wattay International Airport",
        "lat": 17.9883,
        "lng": 102.5633,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 7
    },
    {
        "id": "RIX",
        "name": "Latvia",
        "countryName": "Latvia",
        "flag": "🇱🇻",
        "code": "RIX",
        "airport": "Riga International Airport",
        "lat": 56.9236,
        "lng": 23.9711,
        "visaType": "Sticker Visa",
        "visaProcess": "15-30 working days",
        "timezoneOffset": 3
    },
    {
        "id": "BEY",
        "name": "Lebanon",
        "countryName": "Lebanon",
        "flag": "🇱🇧",
        "code": "BEY",
        "airport": "Beirut-Rafic Hariri Int Airport",
        "lat": 33.8878,
        "lng": 35.4867,
        "visaType": "Visa on Arrival",
        "visaProcess": "5-15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "MSU",
        "name": "Lesotho",
        "countryName": "Lesotho",
        "flag": "🇱🇸",
        "code": "MSU",
        "airport": "Moshoeshoe I International Airport",
        "lat": -29.4622,
        "lng": 27.5525,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 2
    },
    {
        "id": "ROB",
        "name": "Liberia",
        "countryName": "Liberia",
        "flag": "🇱🇷",
        "code": "ROB",
        "airport": "Roberts International Airport",
        "lat": 6.2397,
        "lng": -10.3622,
        "visaType": "e-Visas",
        "visaProcess": "5-7 working days",
        "timezoneOffset": 0
    },
    {
        "id": "TIP",
        "name": "Libya",
        "countryName": "Libya",
        "flag": "🇱🇾",
        "code": "TIP",
        "airport": "Tripoli International Airport",
        "lat": 32.6636,
        "lng": 13.159,
        "visaType": "Sticker Visa",
        "visaProcess": "7 – 12  working days",
        "timezoneOffset": 2
    },
    {
        "id": "ZRH",
        "name": "Liechtenstein",
        "countryName": "Liechtenstein",
        "flag": "🇱🇮",
        "code": "ZRH",
        "airport": "Zurich Airport (via Switzerland)",
        "lat": 47.141,
        "lng": 9.5215,
        "visaType": "Sticker Visa",
        "visaProcess": "15-30 working days",
        "timezoneOffset": 2
    },
    {
        "id": "VNO",
        "name": "Lithuania",
        "countryName": "Lithuania",
        "flag": "🇱🇹",
        "code": "VNO",
        "airport": "Vilnius Airport",
        "lat": 54.6341,
        "lng": 25.2858,
        "visaType": "Sticker Visa",
        "visaProcess": "15-30 working days",
        "timezoneOffset": 3
    },
    {
        "id": "LUX",
        "name": "Luxembourg",
        "countryName": "Luxembourg",
        "flag": "🇱🇺",
        "code": "LUX",
        "airport": "Luxembourg Airport",
        "lat": 49.6233,
        "lng": 6.2044,
        "visaType": "Sticker Visa",
        "visaProcess": "15-20 working days",
        "timezoneOffset": 2
    },
    {
        "id": "TNR",
        "name": "Madagascar",
        "countryName": "Madagascar",
        "flag": "🇲🇬",
        "code": "TNR",
        "airport": "Ivato International Airport",
        "lat": -18.7969,
        "lng": 47.4788,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 3
    },
    {
        "id": "LLW",
        "name": "Malawi",
        "countryName": "Malawi",
        "flag": "🇲🇼",
        "code": "LLW",
        "airport": "Lilongwe International Airport",
        "lat": -13.7833,
        "lng": 33.7803,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 2
    },
    {
        "id": "KUL",
        "name": "Malaysia",
        "countryName": "Malaysia",
        "flag": "🇲🇾",
        "code": "KUL",
        "airport": "Kuala Lumpur International Airport",
        "lat": 2.7456,
        "lng": 101.7072,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 8
    },
    {
        "id": "MLE",
        "name": "Maldives",
        "countryName": "Maldives",
        "flag": "🇲🇻",
        "code": "MLE",
        "airport": "Velana International Airport",
        "lat": 4.1918,
        "lng": 73.5291,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 5
    },
    {
        "id": "BKO",
        "name": "Mali",
        "countryName": "Mali",
        "flag": "🇲🇱",
        "code": "BKO",
        "airport": "Modibo Keita International Airport",
        "lat": 12.5334,
        "lng": -7.9499,
        "visaType": "Sticker Visa",
        "visaProcess": "5-10 working days",
        "timezoneOffset": 0
    },
    {
        "id": "MLA",
        "name": "Malta",
        "countryName": "Malta",
        "flag": "🇲🇹",
        "code": "MLA",
        "airport": "Malta International Airport",
        "lat": 35.8575,
        "lng": 14.4775,
        "visaType": "Sticker Visa",
        "visaProcess": "15-30 working days",
        "timezoneOffset": 2
    },
    {
        "id": "MAJ",
        "name": "Marshall Islands",
        "countryName": "Marshall Islands",
        "flag": "🇲🇭",
        "code": "MAJ",
        "airport": "Amata Kabua International Airport",
        "lat": 7.0647,
        "lng": 171.2722,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 12
    },
    {
        "id": "NKC",
        "name": "Mauritania",
        "countryName": "Mauritania",
        "flag": "🇲🇷",
        "code": "NKC",
        "airport": "Nouakchott-Oumtounsy Int Airport",
        "lat": 18.0982,
        "lng": -15.9472,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 0
    },
    {
        "id": "MRU",
        "name": "Mauritius",
        "countryName": "Mauritius",
        "flag": "🇲🇺",
        "code": "MRU",
        "airport": "Sir Seewoosagur Ramgoolam Airport",
        "lat": -20.43,
        "lng": 57.6836,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 4
    },
    {
        "id": "MEX",
        "name": "Mexico",
        "countryName": "Mexico",
        "flag": "🇲🇽",
        "code": "MEX",
        "airport": "Mexico City International Airport",
        "lat": 19.4361,
        "lng": -99.0719,
        "visaType": "Sticker Visa",
        "visaProcess": "2-5 working days",
        "timezoneOffset": -6
    },
    {
        "id": "PNI",
        "name": "Micronesia",
        "countryName": "Micronesia",
        "flag": "🇫🇲",
        "code": "PNI",
        "airport": "Pohnpei International Airport",
        "lat": 6.9839,
        "lng": 158.2092,
        "visaType": "Visa Free",
        "visaProcess": "7-15 working days",
        "timezoneOffset": 11
    },
    {
        "id": "KIV",
        "name": "Moldova",
        "countryName": "Moldova",
        "flag": "🇲🇩",
        "code": "KIV",
        "airport": "Chișinău International Airport",
        "lat": 46.9278,
        "lng": 28.931,
        "visaType": "e-Visas",
        "visaProcess": "10-20 working days",
        "timezoneOffset": 3
    },
    {
        "id": "NCE",
        "name": "Monaco",
        "countryName": "Monaco",
        "flag": "🇲🇨",
        "code": "NCE",
        "airport": "Nice Côte d'Azur Airport (via France)",
        "lat": 43.7384,
        "lng": 7.4246,
        "visaType": "Sticker Visa",
        "visaProcess": "15-20 working days",
        "timezoneOffset": 2
    },
    {
        "id": "UBN",
        "name": "Mongolia",
        "countryName": "Mongolia",
        "flag": "🇲🇳",
        "code": "UBN",
        "airport": "Chinggis Khaan Int Airport",
        "lat": 47.6516,
        "lng": 106.7664,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 8
    },
    {
        "id": "TGD",
        "name": "Montenegro",
        "countryName": "Montenegro",
        "flag": "🇲🇪",
        "code": "TGD",
        "airport": "Podgorica Airport",
        "lat": 42.3594,
        "lng": 19.2519,
        "visaType": "e-Visas",
        "visaProcess": "7-14 working days",
        "timezoneOffset": 2
    },
    {
        "id": "CMN",
        "name": "Morocco",
        "countryName": "Morocco",
        "flag": "🇲🇦",
        "code": "CMN",
        "airport": "Mohammed V International Airport",
        "lat": 33.3675,
        "lng": -7.5897,
        "visaType": "e-Visas",
        "visaProcess": "3 working days",
        "timezoneOffset": 1
    },
    {
        "id": "MPM",
        "name": "Mozambique",
        "countryName": "Mozambique",
        "flag": "🇲🇿",
        "code": "MPM",
        "airport": "Maputo International Airport",
        "lat": -25.9208,
        "lng": 32.5726,
        "visaType": "e-Visas",
        "visaProcess": "2 to 5 business days",
        "timezoneOffset": 2
    },
    {
        "id": "RGN",
        "name": "Myanmar (Burma)",
        "countryName": "Myanmar",
        "flag": "🇲🇲",
        "code": "RGN",
        "airport": "Yangon International Airport",
        "lat": 16.9073,
        "lng": 96.1332,
        "visaType": "e-Visas",
        "visaProcess": "1-3 working days",
        "timezoneOffset": 6.5
    },
    {
        "id": "WDH",
        "name": "Namibia",
        "countryName": "Namibia",
        "flag": "🇳🇦",
        "code": "WDH",
        "airport": "Hosea Kutako International Airport",
        "lat": -22.4799,
        "lng": 17.4709,
        "visaType": "Sticker Visa",
        "visaProcess": "10 to 15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "INU",
        "name": "Nauru",
        "countryName": "Nauru",
        "flag": "🇳🇷",
        "code": "INU",
        "airport": "Nauru International Airport",
        "lat": -0.5472,
        "lng": 166.9186,
        "visaType": "Visa on Arrival",
        "visaProcess": "7-15 working days",
        "timezoneOffset": 12
    },
    {
        "id": "KTM",
        "name": "Nepal",
        "countryName": "Nepal",
        "flag": "🇳🇵",
        "code": "KTM",
        "airport": "Tribhuvan International Airport",
        "lat": 27.6978,
        "lng": 85.3592,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 5.75
    },
    {
        "id": "AMS",
        "name": "Netherlands",
        "countryName": "Netherlands",
        "flag": "🇳🇱",
        "code": "AMS",
        "airport": "Amsterdam Airport Schiphol",
        "lat": 52.3105,
        "lng": 4.7683,
        "visaType": "Sticker Visa",
        "visaProcess": "15-20 working days",
        "timezoneOffset": 2
    },
    {
        "id": "AKL",
        "name": "New Zealand",
        "countryName": "New Zealand",
        "flag": "🇳🇿",
        "code": "AKL",
        "airport": "Auckland Airport",
        "lat": -37.0081,
        "lng": 174.785,
        "visaType": "e-Visas",
        "visaProcess": "2-4 weeks",
        "timezoneOffset": 12
    },
    {
        "id": "MGA",
        "name": "Nicaragua",
        "countryName": "Nicaragua",
        "flag": "🇳🇮",
        "code": "MGA",
        "airport": "Augusto C. Sandino Int Airport",
        "lat": 12.1419,
        "lng": -86.1681,
        "visaType": "Sticker Visa",
        "visaProcess": "7-15 working days",
        "timezoneOffset": -6
    },
    {
        "id": "NIM",
        "name": "Niger",
        "countryName": "Niger",
        "flag": "🇳🇪",
        "code": "NIM",
        "airport": "Diori Hamani International Airport",
        "lat": 13.4836,
        "lng": 2.1833,
        "visaType": "Sticker Visa",
        "visaProcess": "5 to 7 working days",
        "timezoneOffset": 1
    },
    {
        "id": "LOS",
        "name": "Nigeria",
        "countryName": "Nigeria",
        "flag": "🇳🇬",
        "code": "LOS",
        "airport": "Murtala Muhammed Int Airport",
        "lat": 6.5774,
        "lng": 3.321,
        "visaType": "e-Visas",
        "visaProcess": "2 – 3 working days",
        "timezoneOffset": 1
    },
    {
        "id": "FNJ",
        "name": "North Korea",
        "countryName": "North Korea",
        "flag": "🇰🇵",
        "code": "FNJ",
        "airport": "Sunan International Airport",
        "lat": 39.2239,
        "lng": 125.6703,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 working days",
        "timezoneOffset": 9
    },
    {
        "id": "SKP",
        "name": "North Macedonia",
        "countryName": "Macedonia",
        "flag": "🇲🇰",
        "code": "SKP",
        "airport": "Skopje International Airport",
        "lat": 41.9616,
        "lng": 21.6262,
        "visaType": "Sticker Visa",
        "visaProcess": "15-20 working days",
        "timezoneOffset": 2
    },
    {
        "id": "OSL",
        "name": "Norway",
        "countryName": "Norway",
        "flag": "🇳🇴",
        "code": "OSL",
        "airport": "Oslo Airport Gardermoen",
        "lat": 60.1975,
        "lng": 11.1004,
        "visaType": "Sticker Visa",
        "visaProcess": "12-15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "MCT",
        "name": "Oman",
        "countryName": "Oman",
        "flag": "🇴🇲",
        "code": "MCT",
        "airport": "Muscat International Airport",
        "lat": 23.5933,
        "lng": 58.2811,
        "visaType": "e-Visas",
        "visaProcess": "4-5 working days",
        "timezoneOffset": 4
    },
    {
        "id": "ROR",
        "name": "Palau",
        "countryName": "Palau",
        "flag": "🇵🇼",
        "code": "ROR",
        "airport": "Roman Tmetuchl International Airport",
        "lat": 7.3672,
        "lng": 134.5442,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 9
    },
    {
        "id": "TLV",
        "name": "Palestine",
        "countryName": "Palestine",
        "flag": "🇵🇸",
        "code": "TLV",
        "airport": "Ben Gurion Int Airport (via Israel)",
        "lat": 31.898,
        "lng": 35.2043,
        "visaType": "Sticker Visa",
        "visaProcess": "5 - 10 working days",
        "timezoneOffset": 3
    },
    {
        "id": "PTY",
        "name": "Panama",
        "countryName": "Panama",
        "flag": "🇵🇦",
        "code": "PTY",
        "airport": "Tocumen International Airport",
        "lat": 9.0714,
        "lng": -79.3833,
        "visaType": "Sticker Visa",
        "visaProcess": "20-25 working days",
        "timezoneOffset": -5
    },
    {
        "id": "POM",
        "name": "Papua New Guinea",
        "countryName": "Papua New Guinea",
        "flag": "🇵🇬",
        "code": "POM",
        "airport": "Jacksons International Airport",
        "lat": -9.4434,
        "lng": 147.22,
        "visaType": "e-Visas",
        "visaProcess": "5 working days",
        "timezoneOffset": 10
    },
    {
        "id": "ASU",
        "name": "Paraguay",
        "countryName": "Paraguay",
        "flag": "🇵🇾",
        "code": "ASU",
        "airport": "Silvio Pettirossi International Airport",
        "lat": -25.2397,
        "lng": -57.5192,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": -4
    },
    {
        "id": "LIM",
        "name": "Peru",
        "countryName": "Peru",
        "flag": "🇵🇪",
        "code": "LIM",
        "airport": "Jorge Chávez International Airport",
        "lat": -12.0219,
        "lng": -77.1144,
        "visaType": "e-Visas",
        "visaProcess": "7-10 working days",
        "timezoneOffset": -5
    },
    {
        "id": "MNL",
        "name": "Philippines",
        "countryName": "Philippines",
        "flag": "🇵🇭",
        "code": "MNL",
        "airport": "Ninoy Aquino International Airport",
        "lat": 14.5086,
        "lng": 121.0194,
        "visaType": "Visa Free",
        "visaProcess": "5-10 working days",
        "timezoneOffset": 8
    },
    {
        "id": "WAW",
        "name": "Poland",
        "countryName": "Poland",
        "flag": "🇵🇱",
        "code": "WAW",
        "airport": "Warsaw Chopin Airport",
        "lat": 52.1657,
        "lng": 20.9671,
        "visaType": "Sticker Visa",
        "visaProcess": "12-15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "LIS",
        "name": "Portugal",
        "countryName": "Portugal",
        "flag": "🇵🇹",
        "code": "LIS",
        "airport": "Humberto Delgado Airport",
        "lat": 38.7742,
        "lng": -9.1342,
        "visaType": "Sticker Visa",
        "visaProcess": "15-30 working days",
        "timezoneOffset": 1
    },
    {
        "id": "DOH",
        "name": "Qatar",
        "countryName": "Qatar",
        "flag": "🇶🇦",
        "code": "DOH",
        "airport": "Hamad International Airport",
        "lat": 25.2611,
        "lng": 51.565,
        "visaType": "e-Visas",
        "visaProcess": "5-10 working days",
        "timezoneOffset": 3
    },
    {
        "id": "BZV",
        "name": "Republic of the Congo",
        "countryName": "Republic of the Congo",
        "flag": "🇨🇬",
        "code": "BZV",
        "airport": "Maya-Maya Airport",
        "lat": -4.2517,
        "lng": 15.2528,
        "visaType": "Sticker Visa",
        "visaProcess": "10 to 12 working days",
        "timezoneOffset": 1
    },
    {
        "id": "OTP",
        "name": "Romania",
        "countryName": "Romania",
        "flag": "🇷🇴",
        "code": "OTP",
        "airport": "Henri Coandă International Airport",
        "lat": 44.5711,
        "lng": 26.085,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15  working days",
        "timezoneOffset": 3
    },
    {
        "id": "SVO",
        "name": "Russia",
        "countryName": "Russia",
        "flag": "🇷🇺",
        "code": "SVO",
        "airport": "Sheremetyevo International Airport",
        "lat": 55.9726,
        "lng": 37.4146,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 3
    },
    {
        "id": "KGL",
        "name": "Rwanda",
        "countryName": "Rwanda",
        "flag": "🇷🇼",
        "code": "KGL",
        "airport": "Kigali International Airport",
        "lat": -1.9686,
        "lng": 30.1394,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 2
    },
    {
        "id": "SKB",
        "name": "Saint Kitts and Nevis",
        "countryName": "Saint Kitts and Nevis",
        "flag": "🇰🇳",
        "code": "SKB",
        "airport": "Robert L. Bradshaw Int Airport",
        "lat": 17.3111,
        "lng": -62.7186,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "UVF",
        "name": "Saint Lucia",
        "countryName": "Saint Lucia",
        "flag": "🇱🇨",
        "code": "UVF",
        "airport": "Hewanorra International Airport",
        "lat": 13.7332,
        "lng": -60.9526,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "SVD",
        "name": "Saint Vincent and the Grenadines",
        "countryName": "Saint Vincent and the Grenadines",
        "flag": "🇻🇨",
        "code": "SVD",
        "airport": "Argyle International Airport",
        "lat": 13.1444,
        "lng": -61.2114,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "APW",
        "name": "Samoa",
        "countryName": "Samoa",
        "flag": "🇼🇸",
        "code": "APW",
        "airport": "Faleolo International Airport",
        "lat": -13.8298,
        "lng": -172.0017,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 13
    },
    {
        "id": "BLQ",
        "name": "San Marino",
        "countryName": "San Marino",
        "flag": "🇸🇲",
        "code": "BLQ",
        "airport": "Bologna Airport (via Italy)",
        "lat": 43.9424,
        "lng": 12.4578,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15  working days",
        "timezoneOffset": 2
    },
    {
        "id": "TMS",
        "name": "Sao Tome and Principe",
        "countryName": "Sao Tome and Principe",
        "flag": "🇸🇹",
        "code": "TMS",
        "airport": "São Tomé International Airport",
        "lat": 0.3781,
        "lng": 6.7121,
        "visaType": "e-Visas",
        "visaProcess": "5-7 working days",
        "timezoneOffset": 0
    },
    {
        "id": "RUH",
        "name": "Saudi Arabia",
        "countryName": "Saudi Arabia",
        "flag": "🇸🇦",
        "code": "RUH",
        "airport": "King Khalid International Airport",
        "lat": 24.9576,
        "lng": 46.6988,
        "visaType": "e-Visas",
        "visaProcess": "2-10 working days",
        "timezoneOffset": 3
    },
    {
        "id": "DSS",
        "name": "Senegal",
        "countryName": "Senegal",
        "flag": "🇸🇳",
        "code": "DSS",
        "airport": "Blaise Diagne International Airport",
        "lat": 14.671,
        "lng": -17.0733,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 0
    },
    {
        "id": "BEG",
        "name": "Serbia",
        "countryName": "Serbia",
        "flag": "🇷🇸",
        "code": "BEG",
        "airport": "Belgrade Nikola Tesla Airport",
        "lat": 44.8184,
        "lng": 20.3091,
        "visaType": "Sticker Visa",
        "visaProcess": "12-15  working days",
        "timezoneOffset": 2
    },
    {
        "id": "SEZ",
        "name": "Seychelles",
        "countryName": "Seychelles",
        "flag": "🇸🇨",
        "code": "SEZ",
        "airport": "Seychelles International Airport",
        "lat": -4.6743,
        "lng": 55.5219,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 4
    },
    {
        "id": "FNA",
        "name": "Sierra Leone",
        "countryName": "Sierra Leone",
        "flag": "🇸🇱",
        "code": "FNA",
        "airport": "Lungi International Airport",
        "lat": 8.6164,
        "lng": -13.1956,
        "visaType": "e-Visas",
        "visaProcess": "2 – 3 working days",
        "timezoneOffset": 0
    },
    {
        "id": "SIN",
        "name": "Singapore",
        "countryName": "Singapore",
        "flag": "🇸🇬",
        "code": "SIN",
        "airport": "Singapore Changi Airport",
        "lat": 1.3644,
        "lng": 103.9915,
        "visaType": "e-Visas",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 8
    },
    {
        "id": "BTS",
        "name": "Slovakia",
        "countryName": "Slovakia",
        "flag": "🇸🇰",
        "code": "BTS",
        "airport": "M. R. Štefánik Airport",
        "lat": 48.1702,
        "lng": 17.2127,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15  working days",
        "timezoneOffset": 2
    },
    {
        "id": "LJU",
        "name": "Slovenia",
        "countryName": "Slovenia",
        "flag": "🇸🇮",
        "code": "LJU",
        "airport": "Ljubljana Jože Pučnik Airport",
        "lat": 46.2237,
        "lng": 14.4576,
        "visaType": "Sticker Visa",
        "visaProcess": "12-15  working days",
        "timezoneOffset": 2
    },
    {
        "id": "HIR",
        "name": "Solomon islands",
        "countryName": "Solomon Islands",
        "flag": "🇸🇧",
        "code": "HIR",
        "airport": "Honiara International Airport",
        "lat": -9.428,
        "lng": 160.0547,
        "visaType": "Sticker Visa",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 11
    },
    {
        "id": "MGQ",
        "name": "Somalia",
        "countryName": "Somalia",
        "flag": "🇸🇴",
        "code": "MGQ",
        "airport": "Aden Adde International Airport",
        "lat": 2.0133,
        "lng": 45.3053,
        "visaType": "e-Visas",
        "visaProcess": "3 to 10 working days",
        "timezoneOffset": 3
    },
    {
        "id": "JNB",
        "name": "South  Africa",
        "countryName": "South Africa",
        "flag": "🇿🇦",
        "code": "JNB",
        "airport": "O. R. Tambo International Airport",
        "lat": -26.1392,
        "lng": 28.246,
        "visaType": "e-Visas",
        "visaProcess": "3 to 15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "JUB",
        "name": "South  Sudan",
        "countryName": "South Sudan",
        "flag": "🇸🇸",
        "code": "JUB",
        "airport": "Juba International Airport",
        "lat": 4.872,
        "lng": 31.6011,
        "visaType": "e-Visas",
        "visaProcess": "5 working days",
        "timezoneOffset": 2
    },
    {
        "id": "ICN",
        "name": "South Korea",
        "countryName": "South Korea",
        "flag": "🇰🇷",
        "code": "ICN",
        "airport": "Seoul Incheon Int Airport",
        "lat": 37.4602,
        "lng": 126.4407,
        "visaType": "e-Visas",
        "visaProcess": "10-12 working days",
        "timezoneOffset": 9
    },
    {
        "id": "MAD",
        "name": "Spain",
        "countryName": "Spain",
        "flag": "🇪🇸",
        "code": "MAD",
        "airport": "Adolfo Suárez Madrid–Barajas Airport",
        "lat": 40.4719,
        "lng": -3.5626,
        "visaType": "Sticker Visa",
        "visaProcess": "12-15 working days",
        "timezoneOffset": 2
    },
    {
        "id": "CMB",
        "name": "Sri Lanka",
        "countryName": "Sri Lanka",
        "flag": "🇱🇰",
        "code": "CMB",
        "airport": "Bandaranaike International Airport",
        "lat": 7.1808,
        "lng": 79.8837,
        "visaType": "e-Visas",
        "visaProcess": "within minutes",
        "timezoneOffset": 5.5
    },
    {
        "id": "KRT",
        "name": "Sudan",
        "countryName": "Sudan",
        "flag": "🇸🇩",
        "code": "KRT",
        "airport": "Khartoum International Airport",
        "lat": 15.5895,
        "lng": 32.5531,
        "visaType": "e-Visas",
        "visaProcess": "3 to 4 working days",
        "timezoneOffset": 2
    },
    {
        "id": "PBM",
        "name": "Suriname",
        "countryName": "Suriname",
        "flag": "🇸🇷",
        "code": "PBM",
        "airport": "Johan Adolf Pengel Int Airport",
        "lat": 5.4528,
        "lng": -55.1878,
        "visaType": "e-Visas",
        "visaProcess": "2-3 working  days",
        "timezoneOffset": -3
    },
    {
        "id": "ARN",
        "name": "Sweden",
        "countryName": "Sweden",
        "flag": "🇸🇪",
        "code": "ARN",
        "airport": "Stockholm Arlanda Airport",
        "lat": 59.6519,
        "lng": 17.9186,
        "visaType": "Sticker Visa",
        "visaProcess": "20-25 working days",
        "timezoneOffset": 2
    },
    {
        "id": "ZRH",
        "name": "Switzerland",
        "countryName": "Switzerland",
        "flag": "🇨🇭",
        "code": "ZRH",
        "airport": "Zurich Airport",
        "lat": 47.4581,
        "lng": 8.5481,
        "visaType": "Sticker Visa",
        "visaProcess": "15 to 30 working days",
        "timezoneOffset": 2
    },
    {
        "id": "DAM",
        "name": "Syria",
        "countryName": "Syria",
        "flag": "🇸🇾",
        "code": "DAM",
        "airport": "Damascus International Airport",
        "lat": 33.4114,
        "lng": 36.5139,
        "visaType": "Sticker Visa",
        "visaProcess": "5-15 working days",
        "timezoneOffset": 3
    },
    {
        "id": "TPE",
        "name": "Taiwan",
        "countryName": "Taiwan",
        "flag": "🇹🇼",
        "code": "TPE",
        "airport": "Taoyuan International Airport",
        "lat": 25.0797,
        "lng": 121.2342,
        "visaType": "e-Visas",
        "visaProcess": "5-7 working days",
        "timezoneOffset": 8
    },
    {
        "id": "DYU",
        "name": "Tajikistan",
        "countryName": "Tajikistan",
        "flag": "🇹🇯",
        "code": "DYU",
        "airport": "Dushanbe International Airport",
        "lat": 38.5433,
        "lng": 68.8249,
        "visaType": "e-Visas",
        "visaProcess": "2 to 5 working days",
        "timezoneOffset": 5
    },
    {
        "id": "DAR",
        "name": "Tanzania",
        "countryName": "Tanzania",
        "flag": "🇹🇿",
        "code": "DAR",
        "airport": "Julius Nyerere International Airport",
        "lat": -6.8781,
        "lng": 39.2026,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 3
    },
    {
        "id": "BKK",
        "name": "Thailand",
        "countryName": "Thailand",
        "flag": "🇹🇭",
        "code": "BKK",
        "airport": "Suvarnabhumi Airport",
        "lat": 13.69,
        "lng": 100.7501,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": 7
    },
    {
        "id": "DIL",
        "name": "Timor Leste",
        "countryName": "Timor-Leste",
        "flag": "🇹🇱",
        "code": "DIL",
        "airport": "Presidente Nicolau Lobato Int Airport",
        "lat": -8.5472,
        "lng": 125.5294,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 9
    },
    {
        "id": "LFW",
        "name": "Togo",
        "countryName": "Togo",
        "flag": "🇹🇬",
        "code": "LFW",
        "airport": "Lomé-Tokoin Airport",
        "lat": 6.1656,
        "lng": 1.2544,
        "visaType": "e-Visas",
        "visaProcess": "5 – 7 Business Days",
        "timezoneOffset": 0
    },
    {
        "id": "TBU",
        "name": "Tonga",
        "countryName": "Tonga",
        "flag": "🇹🇴",
        "code": "TBU",
        "airport": "Fuaʻamotu International Airport",
        "lat": -21.2408,
        "lng": -175.1381,
        "visaType": "Visa on Arrival",
        "visaProcess": "10 -15 working days",
        "timezoneOffset": 13
    },
    {
        "id": "POS",
        "name": "Trinidad and Tobago",
        "countryName": "Trinidad and Tobago",
        "flag": "🇹🇹",
        "code": "POS",
        "airport": "Piarco International Airport",
        "lat": 10.5954,
        "lng": -61.3372,
        "visaType": "Visa Free",
        "visaProcess": "within minutes",
        "timezoneOffset": -4
    },
    {
        "id": "TUN",
        "name": "Tunisia",
        "countryName": "Tunisia",
        "flag": "🇹🇳",
        "code": "TUN",
        "airport": "Tunis-Carthage International Airport",
        "lat": 36.851,
        "lng": 10.2272,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 working days",
        "timezoneOffset": 1
    },
    {
        "id": "IST",
        "name": "Turkiye",
        "countryName": "Turkey",
        "flag": "🇹🇷",
        "code": "IST",
        "airport": "Istanbul Airport",
        "lat": 41.2752,
        "lng": 28.7519,
        "visaType": "e-Visas",
        "visaProcess": "1 -2 Working days",
        "timezoneOffset": 3
    },
    {
        "id": "ASB",
        "name": "Turkmenistan",
        "countryName": "Turkmenistan",
        "flag": "🇹🇲",
        "code": "ASB",
        "airport": "Ashgabat International Airport",
        "lat": 37.9867,
        "lng": 58.3611,
        "visaType": "Sticker Visa",
        "visaProcess": "10-15 working days",
        "timezoneOffset": 5
    },
    {
        "id": "FUN",
        "name": "Tuvalu",
        "countryName": "Tuvalu",
        "flag": "🇹🇻",
        "code": "FUN",
        "airport": "Funafuti International Airport",
        "lat": -8.5244,
        "lng": 179.1961,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 12
    },
    {
        "id": "EBB",
        "name": "Uganda",
        "countryName": "Uganda",
        "flag": "🇺🇬",
        "code": "EBB",
        "airport": "Entebbe International Airport",
        "lat": 0.0424,
        "lng": 32.4435,
        "visaType": "e-Visas",
        "visaProcess": "3 to 5 business days",
        "timezoneOffset": 3
    },
    {
        "id": "KBP",
        "name": "Ukraine",
        "countryName": "Ukraine",
        "flag": "🇺🇦",
        "code": "KBP",
        "airport": "Boryspil International Airport",
        "lat": 50.345,
        "lng": 30.8947,
        "visaType": "e-Visas",
        "visaProcess": "10-30  working days",
        "timezoneOffset": 3
    },
    {
        "id": "LHR",
        "name": "United Kingdom (UK)",
        "countryName": "United Kingdom",
        "flag": "🇬🇧",
        "code": "LHR",
        "airport": "London Heathrow Airport",
        "lat": 51.47,
        "lng": -0.4543,
        "visaType": "e-Visas",
        "visaProcess": "15 to 20 working days",
        "timezoneOffset": 1
    },
    {
        "id": "JFK",
        "name": "United States of America (USA)",
        "countryName": "United States",
        "flag": "🇺🇸",
        "code": "JFK",
        "airport": "John F. Kennedy Int Airport",
        "lat": 40.6413,
        "lng": -73.7781,
        "visaType": "Sticker Visa",
        "visaProcess": "20-30 working days",
        "timezoneOffset": -5
    },
    {
        "id": "MVD",
        "name": "Uruguay",
        "countryName": "Uruguay",
        "flag": "🇺🇾",
        "code": "MVD",
        "airport": "Carrasco International Airport",
        "lat": -34.8384,
        "lng": -56.0308,
        "visaType": "Sticker Visa",
        "visaProcess": "10 to 15 business days",
        "timezoneOffset": -3
    },
    {
        "id": "TAS",
        "name": "Uzbekistan",
        "countryName": "Uzbekistan",
        "flag": "🇺🇿",
        "code": "TAS",
        "airport": "Tashkent International Airport",
        "lat": 41.2579,
        "lng": 69.2812,
        "visaType": "e-Visas",
        "visaProcess": "2 to 3 working days",
        "timezoneOffset": 5
    },
    {
        "id": "VLI",
        "name": "Vanuatu",
        "countryName": "Vanuatu",
        "flag": "🇻🇺",
        "code": "VLI",
        "airport": "Bauerfield International Airport",
        "lat": -17.6992,
        "lng": 168.32,
        "visaType": "Visa Free",
        "visaProcess": "3-5 working days",
        "timezoneOffset": 11
    },
    {
        "id": "CCS",
        "name": "Venezuela",
        "countryName": "Venezuela",
        "flag": "🇻🇪",
        "code": "CCS",
        "airport": "Simón Bolívar International Airport",
        "lat": 10.6031,
        "lng": -66.9906,
        "visaType": "Sticker Visa",
        "visaProcess": "10 to 15 business days",
        "timezoneOffset": -4
    },
    {
        "id": "HAN",
        "name": "Vietnam",
        "countryName": "Vietnam",
        "flag": "🇻🇳",
        "code": "HAN",
        "airport": "Noi Bai International Airport",
        "lat": 21.2212,
        "lng": 105.8072,
        "visaType": "e-Visas",
        "visaProcess": "3-7 working days",
        "timezoneOffset": 7
    },
    {
        "id": "SAH",
        "name": "Yemen",
        "countryName": "Yemen",
        "flag": "🇾🇪",
        "code": "SAH",
        "airport": "Sana'a International Airport",
        "lat": 15.4764,
        "lng": 44.2197,
        "visaType": "Sticker Visa",
        "visaProcess": "2-7 working days",
        "timezoneOffset": 3
    },
    {
        "id": "LUN",
        "name": "Zambia",
        "countryName": "Zambia",
        "flag": "🇿🇲",
        "code": "LUN",
        "airport": "Kenneth Kaunda International Airport",
        "lat": -15.3308,
        "lng": 28.4526,
        "visaType": "e-Visas",
        "visaProcess": "3-7 working days",
        "timezoneOffset": 2
    },
    {
        "id": "HRE",
        "name": "Zimbabwe",
        "countryName": "Zimbabwe",
        "flag": "🇿🇼",
        "code": "HRE",
        "airport": "Harare International Airport",
        "lat": -17.9318,
        "lng": 31.0928,
        "visaType": "Visa on Arrival",
        "visaProcess": "within minutes",
        "timezoneOffset": 2
    }
];
